require('dotenv').config();
const https=require('https'),fs=require('fs'),path=require('path');
const startpairing=require('./pair.js');
const TOKEN=process.env.BOT_TOKEN||process.env.TELEGRAM_BOT_TOKEN||(()=>{try{const t=require('./token.js');return t.BOT_TOKEN||t.token||t.default||''}catch{return ''}})();
if(!TOKEN) throw new Error('Set BOT_TOKEN/TELEGRAM_BOT_TOKEN or export BOT_TOKEN from token.js');
const API=`https://api.telegram.org/bot${TOKEN}`, root=path.join(__dirname,'kingbadboitimewisher','pairing'), file=path.join(root,'pairing.json'), banner=path.join(__dirname,'media','annie-brand.png');let offset=0,busy=false; const pendingNumbers=new Set();
function tg(method,body={}){return new Promise((res,rej)=>{const q=https.request(`${API}/${method}`,{method:'POST',headers:{'content-type':'application/json'}},r=>{let d='';r.on('data',x=>d+=x);r.on('end',()=>{try{const j=JSON.parse(d);j.ok?res(j.result):rej(Error(j.description||'Telegram error'))}catch(e){rej(e)}})});q.on('error',rej);q.end(JSON.stringify(body))})}
function tgPhoto(chatId,caption,keyboard){return new Promise((res,rej)=>{const boundary=`----annie${Date.now()}`,parts=[];const add=(name,value)=>parts.push(Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`));add('chat_id',chatId);add('caption',caption);add('parse_mode','HTML');add('reply_markup',JSON.stringify(keyboard));const img=fs.readFileSync(banner);parts.push(Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="photo"; filename="annie-brand.png"\r\nContent-Type: image/png\r\n\r\n`),img,Buffer.from(`\r\n--${boundary}--\r\n`)]));const body=Buffer.concat(parts);const q=https.request(`${API}/sendPhoto`,{method:'POST',headers:{'content-type':`multipart/form-data; boundary=${boundary}`,'content-length':body.length}},r=>{let d='';r.on('data',x=>d+=x);r.on('end',()=>{try{const j=JSON.parse(d);j.ok?res(j.result):rej(Error(j.description||'Telegram photo error'))}catch(e){rej(e)}})});q.on('error',rej);q.end(body)})}
const num=x=>{const n=String(x||'').replace(/\D/g,'');return n.length>=7&&n.length<=15?n:null};
async function code(n){fs.mkdirSync(root,{recursive:true});try{fs.unlinkSync(file)}catch{}await startpairing(`${n}@s.whatsapp.net`);const end=Date.now()+70000;while(Date.now()<end){try{const j=JSON.parse(fs.readFileSync(file));if(j.error)throw Error(j.error);if(j.code)return j.code}catch(e){if(e.message.startsWith('WhatsApp pairing failed:'))throw e}await new Promise(r=>setTimeout(r,500))}throw Error('Pairing code timed out')}
const keyboard={inline_keyboard:[[{text:'🔗 Pair Now',style:'primary',callback_data:'pair'}],[{text:'📖 Pairing Help',style:'primary',callback_data:'help'}]]};
const welcome=(user)=>`<b>☠︎︎ ANNIE MD ☠</b>\n\n<b>Welcome, ${user.first_name||'there'}${user.username?` (@${user.username})`:''}.</b>\n\nPremium WhatsApp pairing center.\n\nTap <b>Pair Now</b>, send your full international WhatsApp number, and receive your secure pairing code.`;
async function handle(m){const id=m.chat?.id;if(!id)return;const t=(m.text||'').trim();if(t==='/start'||t==='/help')return tgPhoto(id,welcome(m.from||{}),keyboard).catch(()=>tg('sendMessage',{chat_id:id,text:welcome(m.from||{}).replace(/<[^>]+>/g,''),reply_markup:keyboard}));if(m.callback_query){ const cq=m.callback_query; await tg('answerCallbackQuery',{callback_query_id:cq.id}); if(cq.data==='help') return tg('sendMessage',{chat_id:id,text:'Send your WhatsApp number in full international format, for example: 923001234567.'}); pendingNumbers.add(String(id)); return tg('sendMessage',{chat_id:id,text:'🔗 <b>Pair Now</b>\n\nSend your full international WhatsApp number now. Example: <code>923001234567</code>',parse_mode:'HTML',reply_markup:{force_reply:true,input_field_placeholder:'923001234567'}});}if(pendingNumbers.has(String(id)) && !t.startsWith('/')){ pendingNumbers.delete(String(id)); return handle({...m,text:'/pair '+t}); } if(t.startsWith('/pair')){if(busy)return tg('sendMessage',{chat_id:id,text:'⏳ Another pairing request is already running. Please wait.'});const n=num(t.split(/\s+/)[1]);if(!n)return tg('sendMessage',{chat_id:id,text:'Usage: /pair 923001234567'});busy=true;try{const c=await code(n);await tg('sendMessage',{chat_id:id,text:`✅ <b>ANNIE MD PAIRING CONSOLE</b>\n\n<pre>╭────────────────────╮\n│   PAIRING CODE     │\n│      ${c}          │\n╰────────────────────╯</pre>\nEnter this in WhatsApp → Linked devices → Link with phone number.`,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'📋 Copy pairing code',style:'success',copy_text:{text:c}}],[{text:'🔗 Pair another number',style:'primary',callback_data:'pair'}]]}})}catch(e){await tg('sendMessage',{chat_id:id,text:`❌ Pairing failed: ${e.message}`})}finally{busy=false}}}
async function loop(){try{for(const u of await tg('getUpdates',{timeout:25,offset})){offset=u.update_id+1;await handle(u.callback_query?{...u.callback_query.message,callback_query:u.callback_query}:u.message)}}catch(e){console.error('Telegram:',e.message);await new Promise(r=>setTimeout(r,3000))}setImmediate(loop)}
async function startTelegram(){await tg('deleteWebhook',{drop_pending_updates:false});const me=await tg('getMe');console.log(`☠︎︎ ANNIE MD ☠ Telegram bot connected as @${me.username||me.first_name}`);loop()}
startTelegram().catch(e=>{console.error('Telegram startup failed:',e.message);process.exit(1)});
